
name: lab8

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        version: [6,7,8]
    runs-on: windows-latest;
    
    steps:
      - uses: actions/checkout@v4
      - name: Build project on different versions
        run: dotnet build ./src/lab.csproj
